// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package reviewdb

import (
	"context"
	"time"
)

const createReason = `-- name: CreateReason :one
INSERT INTO moderation_reasons (code, label, description) VALUES ($1, $2, $3)
RETURNING id, is_active, created_at, updated_at
`

type CreateReasonParams struct {
	Code        string
	Label       string
	Description *string
}

type CreateReasonRow struct {
	ID        string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateReason(ctx context.Context, arg CreateReasonParams) (CreateReasonRow, error) {
	row := q.db.QueryRow(ctx, createReason, arg.Code, arg.Label, arg.Description)
	var i CreateReasonRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO review_reports (review_id, reporting_vendor_id, reason_id, reason_code, reason_label, note)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, status, created_at, updated_at
`

type CreateReportParams struct {
	ReviewID          string
	ReportingVendorID string
	ReasonID          string
	ReasonCode        string
	ReasonLabel       string
	Note              *string
}

type CreateReportRow struct {
	ID        string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReviewID,
		arg.ReportingVendorID,
		arg.ReasonID,
		arg.ReasonCode,
		arg.ReasonLabel,
		arg.Note,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReason = `-- name: GetReason :one
SELECT id, code, label, description, is_active, created_at, updated_at FROM moderation_reasons WHERE id = $1
`

func (q *Queries) GetReason(ctx context.Context, id string) (ModerationReason, error) {
	row := q.db.QueryRow(ctx, getReason, id)
	var i ModerationReason
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportForUpdate = `-- name: GetReportForUpdate :one
SELECT id, review_id, reporting_vendor_id, reason_id, reason_code, reason_label, note, status, decision, resolution_reason_id, resolved_by, resolved_at, resolution_note, created_at, updated_at FROM review_reports WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetReportForUpdate(ctx context.Context, id string) (ReviewReport, error) {
	row := q.db.QueryRow(ctx, getReportForUpdate, id)
	var i ReviewReport
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ReportingVendorID,
		&i.ReasonID,
		&i.ReasonCode,
		&i.ReasonLabel,
		&i.Note,
		&i.Status,
		&i.Decision,
		&i.ResolutionReasonID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideReview = `-- name: HideReview :execrows
UPDATE reviews SET status = 'hidden', hidden_reason_id = $1::uuid, hidden_by = $2::uuid,
    hidden_note = $3, hidden_at = now(), updated_at = now()
WHERE id = $4 AND status = 'published'
`

type HideReviewParams struct {
	HiddenReasonID string
	HiddenBy       string
	HiddenNote     *string
	ID             string
}

func (q *Queries) HideReview(ctx context.Context, arg HideReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideReview,
		arg.HiddenReasonID,
		arg.HiddenBy,
		arg.HiddenNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO review_moderation_audit_logs (review_id, report_id, reason_id, actor_id, action, note, request_id, entity_type,
    entity_id, changes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditParams struct {
	ReviewID   *string
	ReportID   *string
	ReasonID   *string
	ActorID    string
	Action     string
	Note       *string
	RequestID  *string
	EntityType string
	EntityID   string
	Changes    []byte
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ReviewID,
		arg.ReportID,
		arg.ReasonID,
		arg.ActorID,
		arg.Action,
		arg.Note,
		arg.RequestID,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
	)
	return err
}

const listReasons = `-- name: ListReasons :many
SELECT id, code, label, description, is_active, created_at, updated_at FROM moderation_reasons WHERE ($1::boolean = false OR is_active) ORDER BY label
`

func (q *Queries) ListReasons(ctx context.Context, activeOnly bool) ([]ModerationReason, error) {
	rows, err := q.db.Query(ctx, listReasons, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationReason
	for rows.Next() {
		var i ModerationReason
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT rr.id, rr.review_id, rr.reporting_vendor_id, rr.reason_id, rr.reason_code, rr.reason_label, rr.note, rr.status, rr.decision, rr.resolution_reason_id, rr.resolved_by, rr.resolved_at, rr.resolution_note, rr.created_at, rr.updated_at FROM review_reports rr JOIN reviews r ON r.id = rr.review_id
WHERE ($1::text = '' OR rr.status = $1::text) AND ($2::text = '' OR r.vendor_id::text = $2::text)
    AND ($3::text = '' OR r.product_id::text = $3::text)
ORDER BY rr.created_at DESC, rr.id LIMIT $5::int OFFSET $4::int
`

type ListReportsParams struct {
	Status     string
	VendorID   string
	ProductID  string
	PageOffset int
	PageLimit  int
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ReviewReport, error) {
	rows, err := q.db.Query(ctx, listReports,
		arg.Status,
		arg.VendorID,
		arg.ProductID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReport
	for rows.Next() {
		var i ReviewReport
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ReportingVendorID,
			&i.ReasonID,
			&i.ReasonCode,
			&i.ReasonLabel,
			&i.Note,
			&i.Status,
			&i.Decision,
			&i.ResolutionReasonID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const operations = `-- name: Operations :one
SELECT
    (SELECT count(*) FROM review_reports WHERE status = 'open')::bigint AS open_reports,
    (SELECT COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)) / 3600, 0)::bigint FROM review_reports WHERE status = 'open')::bigint
        AS oldest_open_report_hours,
    (SELECT count(*) FROM reviews WHERE status = 'hidden' AND hidden_at > now() - interval '7 days')::bigint AS hidden_7d,
    (SELECT count(*) FROM reviews WHERE created_at > now() - interval '24 hours')::bigint AS reviews_24h,
    (SELECT count(*) FROM review_image_uploads WHERE parked_at IS NULL AND created_at < now() - interval '1 hour')::bigint
        AS image_cleanup_pending,
    (SELECT count(*) FROM review_image_uploads WHERE parked_at IS NOT NULL)::bigint AS image_cleanup_parked,
    (SELECT count(*) FROM reviews WHERE author_label_checked_at IS NULL)::bigint AS author_labels_pending
`

type OperationsRow struct {
	OpenReports           int64
	OldestOpenReportHours int64
	Hidden7d              int64
	Reviews24h            int64
	ImageCleanupPending   int64
	ImageCleanupParked    int64
	AuthorLabelsPending   int64
}

// The moderation and upload report (admin dashboard).
func (q *Queries) Operations(ctx context.Context) (OperationsRow, error) {
	row := q.db.QueryRow(ctx, operations)
	var i OperationsRow
	err := row.Scan(
		&i.OpenReports,
		&i.OldestOpenReportHours,
		&i.Hidden7d,
		&i.Reviews24h,
		&i.ImageCleanupPending,
		&i.ImageCleanupParked,
		&i.AuthorLabelsPending,
	)
	return i, err
}

const resolveReport = `-- name: ResolveReport :execrows
UPDATE review_reports SET status = 'resolved', decision = $1::text, resolution_reason_id = $2,
    resolved_by = $3::uuid, resolved_at = now(), resolution_note = $4, updated_at = now()
WHERE id = $5 AND status = 'open'
`

type ResolveReportParams struct {
	Decision           string
	ResolutionReasonID *string
	ResolvedBy         string
	ResolutionNote     *string
	ID                 string
}

// Closes an open report; 0 rows means it was not open.
func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveReport,
		arg.Decision,
		arg.ResolutionReasonID,
		arg.ResolvedBy,
		arg.ResolutionNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreReview = `-- name: RestoreReview :execrows
UPDATE reviews SET status = 'published', hidden_reason_id = NULL, hidden_by = NULL, hidden_note = NULL, hidden_at = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'hidden'
`

func (q *Queries) RestoreReview(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, restoreReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReason = `-- name: UpdateReason :one
UPDATE moderation_reasons SET code = $1, label = $2, description = $3, is_active = $4, updated_at = now()
WHERE id = $5 RETURNING updated_at
`

type UpdateReasonParams struct {
	Code        string
	Label       string
	Description *string
	IsActive    bool
	ID          string
}

func (q *Queries) UpdateReason(ctx context.Context, arg UpdateReasonParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateReason,
		arg.Code,
		arg.Label,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
