// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reviewdb

import (
	"time"
)

type ModerationReason struct {
	ID          string
	Code        string
	Label       string
	Description *string
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Review struct {
	ID                   string
	BuyerID              string
	VendorID             string
	ProductID            string
	OrderItemID          string
	VendorOrderID        string
	Rating               int
	Comment              string
	Status               string
	HiddenReasonID       *string
	HiddenBy             *string
	HiddenAt             *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	VerifiedPurchase     bool
	AuthorLabel          *string
	AuthorLabelCheckedAt *time.Time
	HiddenNote           *string
}

type ReviewImage struct {
	ID          string
	ReviewID    string
	ObjectKey   string
	URL         string
	ContentType string
	SizeBytes   int64
	Position    int
	CreatedAt   time.Time
}

type ReviewImageUpload struct {
	ObjectKey     string
	ReviewID      string
	CreatedAt     time.Time
	Attempts      int
	NextAttemptAt time.Time
	LastError     *string
	ParkedAt      *time.Time
}

type ReviewModerationAuditLog struct {
	ID         string
	ReviewID   *string
	ReportID   *string
	ReasonID   *string
	ActorID    string
	Action     string
	Note       *string
	CreatedAt  time.Time
	RequestID  *string
	EntityType string
	EntityID   string
	Changes    []byte
}

type ReviewReply struct {
	ReviewID  string
	VendorID  string
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ReviewReport struct {
	ID                 string
	ReviewID           string
	ReportingVendorID  string
	ReasonID           string
	ReasonCode         string
	ReasonLabel        string
	Note               *string
	Status             string
	Decision           *string
	ResolutionReasonID *string
	ResolvedBy         *string
	ResolvedAt         *time.Time
	ResolutionNote     *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
