// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package reviewdb

import (
	"context"
	"time"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, verified_purchase,
    author_label, author_label_checked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
    $9, CASE WHEN $10::boolean THEN now() END)
RETURNING id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note
`

type CreateReviewParams struct {
	BuyerID          string
	VendorID         string
	ProductID        string
	OrderItemID      string
	VendorOrderID    string
	Rating           int
	Comment          string
	VerifiedPurchase bool
	AuthorLabel      *string
	LabelChecked     bool
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.BuyerID,
		arg.VendorID,
		arg.ProductID,
		arg.OrderItemID,
		arg.VendorOrderID,
		arg.Rating,
		arg.Comment,
		arg.VerifiedPurchase,
		arg.AuthorLabel,
		arg.LabelChecked,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.VendorID,
		&i.ProductID,
		&i.OrderItemID,
		&i.VendorOrderID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.HiddenReasonID,
		&i.HiddenBy,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedPurchase,
		&i.AuthorLabel,
		&i.AuthorLabelCheckedAt,
		&i.HiddenNote,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.VendorID,
		&i.ProductID,
		&i.OrderItemID,
		&i.VendorOrderID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.HiddenReasonID,
		&i.HiddenBy,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedPurchase,
		&i.AuthorLabel,
		&i.AuthorLabelCheckedAt,
		&i.HiddenNote,
	)
	return i, err
}

const getReviewForUpdate = `-- name: GetReviewForUpdate :one
SELECT id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note FROM reviews WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetReviewForUpdate(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewForUpdate, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.VendorID,
		&i.ProductID,
		&i.OrderItemID,
		&i.VendorOrderID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.HiddenReasonID,
		&i.HiddenBy,
		&i.HiddenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedPurchase,
		&i.AuthorLabel,
		&i.AuthorLabelCheckedAt,
		&i.HiddenNote,
	)
	return i, err
}

const imagesForReviews = `-- name: ImagesForReviews :many
SELECT id, review_id, object_key, url, content_type, size_bytes, position, created_at FROM review_images WHERE review_id = ANY($1::uuid[]) ORDER BY review_id, position
`

func (q *Queries) ImagesForReviews(ctx context.Context, reviewIds []string) ([]ReviewImage, error) {
	rows, err := q.db.Query(ctx, imagesForReviews, reviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewImage
	for rows.Next() {
		var i ReviewImage
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ObjectKey,
			&i.URL,
			&i.ContentType,
			&i.SizeBytes,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminReviews = `-- name: ListAdminReviews :many
SELECT id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note FROM reviews
WHERE ($1::text = '' OR buyer_id::text = $1::text) AND ($2::text = '' OR vendor_id::text = $2::text)
    AND ($3::text = '' OR product_id::text = $3::text) AND ($4::text = '' OR status = $4::text)
    AND ($5::int = 0 OR rating = $5::int)
ORDER BY created_at DESC, id LIMIT $7::int OFFSET $6::int
`

type ListAdminReviewsParams struct {
	BuyerID    string
	VendorID   string
	ProductID  string
	Status     string
	Rating     int
	PageOffset int
	PageLimit  int
}

func (q *Queries) ListAdminReviews(ctx context.Context, arg ListAdminReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listAdminReviews,
		arg.BuyerID,
		arg.VendorID,
		arg.ProductID,
		arg.Status,
		arg.Rating,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.VendorID,
			&i.ProductID,
			&i.OrderItemID,
			&i.VendorOrderID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.HiddenReasonID,
			&i.HiddenBy,
			&i.HiddenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedPurchase,
			&i.AuthorLabel,
			&i.AuthorLabelCheckedAt,
			&i.HiddenNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuyerReviews = `-- name: ListBuyerReviews :many
SELECT id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note FROM reviews WHERE buyer_id = $1
ORDER BY created_at DESC, id LIMIT $3::int OFFSET $2::int
`

type ListBuyerReviewsParams struct {
	BuyerID    string
	PageOffset int
	PageLimit  int
}

func (q *Queries) ListBuyerReviews(ctx context.Context, arg ListBuyerReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listBuyerReviews, arg.BuyerID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.VendorID,
			&i.ProductID,
			&i.OrderItemID,
			&i.VendorOrderID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.HiddenReasonID,
			&i.HiddenBy,
			&i.HiddenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedPurchase,
			&i.AuthorLabel,
			&i.AuthorLabelCheckedAt,
			&i.HiddenNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicReviews = `-- name: ListPublicReviews :many
SELECT id, buyer_id, vendor_id, product_id, order_item_id, vendor_order_id, rating, comment, status, hidden_reason_id, hidden_by, hidden_at, created_at, updated_at, verified_purchase, author_label, author_label_checked_at, hidden_note FROM reviews
WHERE product_id = $1 AND status = 'published' AND (verified_purchase OR $2::boolean)
    AND ($3::int = 0 OR rating = $3::int)
ORDER BY created_at DESC, id LIMIT $5::int OFFSET $4::int
`

type ListPublicReviewsParams struct {
	ProductID         string
	IncludeUnverified bool
	Rating            int
	PageOffset        int
	PageLimit         int
}

func (q *Queries) ListPublicReviews(ctx context.Context, arg ListPublicReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listPublicReviews,
		arg.ProductID,
		arg.IncludeUnverified,
		arg.Rating,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.VendorID,
			&i.ProductID,
			&i.OrderItemID,
			&i.VendorOrderID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.HiddenReasonID,
			&i.HiddenBy,
			&i.HiddenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedPurchase,
			&i.AuthorLabel,
			&i.AuthorLabelCheckedAt,
			&i.HiddenNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorReviews = `-- name: ListVendorReviews :many
SELECT r.id, r.buyer_id, r.vendor_id, r.product_id, r.order_item_id, r.vendor_order_id, r.rating, r.comment, r.status, r.hidden_reason_id, r.hidden_by, r.hidden_at, r.created_at, r.updated_at, r.verified_purchase, r.author_label, r.author_label_checked_at, r.hidden_note FROM reviews r
WHERE r.vendor_id = $1 AND r.status = 'published' AND (r.verified_purchase OR $2::boolean)
    AND ($3::text = '' OR r.product_id::text = $3::text) AND ($4::int = 0 OR r.rating = $4::int)
    AND ($5::boolean IS NULL
        OR $5::boolean = EXISTS (SELECT 1 FROM review_replies rr WHERE rr.review_id = r.id))
ORDER BY r.created_at DESC, r.id LIMIT $7::int OFFSET $6::int
`

type ListVendorReviewsParams struct {
	VendorID          string
	IncludeUnverified bool
	ProductID         string
	Rating            int
	Replied           *bool
	PageOffset        int
	PageLimit         int
}

// replied: nil = all, true = with a shop reply, false = without one.
func (q *Queries) ListVendorReviews(ctx context.Context, arg ListVendorReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listVendorReviews,
		arg.VendorID,
		arg.IncludeUnverified,
		arg.ProductID,
		arg.Rating,
		arg.Replied,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.VendorID,
			&i.ProductID,
			&i.OrderItemID,
			&i.VendorOrderID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.HiddenReasonID,
			&i.HiddenBy,
			&i.HiddenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedPurchase,
			&i.AuthorLabel,
			&i.AuthorLabelCheckedAt,
			&i.HiddenNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReplyMessage = `-- name: LockReplyMessage :one
SELECT message FROM review_replies WHERE review_id = $1 FOR UPDATE
`

func (q *Queries) LockReplyMessage(ctx context.Context, reviewID string) (string, error) {
	row := q.db.QueryRow(ctx, lockReplyMessage, reviewID)
	var message string
	err := row.Scan(&message)
	return message, err
}

const pendingLabels = `-- name: PendingLabels :many
SELECT id AS review_id, buyer_id FROM reviews WHERE author_label_checked_at IS NULL
ORDER BY created_at LIMIT $1::int
`

type PendingLabelsRow struct {
	ReviewID string
	BuyerID  string
}

func (q *Queries) PendingLabels(ctx context.Context, batchSize int) ([]PendingLabelsRow, error) {
	rows, err := q.db.Query(ctx, pendingLabels, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingLabelsRow
	for rows.Next() {
		var i PendingLabelsRow
		if err := rows.Scan(&i.ReviewID, &i.BuyerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productSummary = `-- name: ProductSummary :one

SELECT COALESCE(avg(rating), 0)::float8 AS rating_average, count(*) AS rating_count,
    count(*) FILTER (WHERE rating = 1) AS rated_1, count(*) FILTER (WHERE rating = 2) AS rated_2,
    count(*) FILTER (WHERE rating = 3) AS rated_3, count(*) FILTER (WHERE rating = 4) AS rated_4,
    count(*) FILTER (WHERE rating = 5) AS rated_5
FROM reviews WHERE product_id = $1 AND status = 'published' AND (verified_purchase OR $2::boolean)
`

type ProductSummaryParams struct {
	ProductID         string
	IncludeUnverified bool
}

type ProductSummaryRow struct {
	RatingAverage float64
	RatingCount   int64
	Rated1        int64
	Rated2        int64
	Rated3        int64
	Rated4        int64
	Rated5        int64
}

// The two summaries count exactly what the public lists can show; they
// differ only in the scope column (each has its own index).
func (q *Queries) ProductSummary(ctx context.Context, arg ProductSummaryParams) (ProductSummaryRow, error) {
	row := q.db.QueryRow(ctx, productSummary, arg.ProductID, arg.IncludeUnverified)
	var i ProductSummaryRow
	err := row.Scan(
		&i.RatingAverage,
		&i.RatingCount,
		&i.Rated1,
		&i.Rated2,
		&i.Rated3,
		&i.Rated4,
		&i.Rated5,
	)
	return i, err
}

const repliesForReviews = `-- name: RepliesForReviews :many
SELECT review_id, vendor_id, message, created_at, updated_at FROM review_replies WHERE review_id = ANY($1::uuid[])
`

func (q *Queries) RepliesForReviews(ctx context.Context, reviewIds []string) ([]ReviewReply, error) {
	rows, err := q.db.Query(ctx, repliesForReviews, reviewIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReply
	for rows.Next() {
		var i ReviewReply
		if err := rows.Scan(
			&i.ReviewID,
			&i.VendorID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewedItemIDs = `-- name: ReviewedItemIDs :many
SELECT order_item_id FROM reviews WHERE buyer_id = $1
`

func (q *Queries) ReviewedItemIDs(ctx context.Context, buyerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, reviewedItemIDs, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var order_item_id string
		if err := rows.Scan(&order_item_id); err != nil {
			return nil, err
		}
		items = append(items, order_item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLabel = `-- name: SetLabel :exec
UPDATE reviews SET author_label = $1, author_label_checked_at = now() WHERE id = $2
`

type SetLabelParams struct {
	AuthorLabel *string
	ID          string
}

func (q *Queries) SetLabel(ctx context.Context, arg SetLabelParams) error {
	_, err := q.db.Exec(ctx, setLabel, arg.AuthorLabel, arg.ID)
	return err
}

const upsertReply = `-- name: UpsertReply :one
INSERT INTO review_replies (review_id, vendor_id, message) VALUES ($1, $2, $3)
ON CONFLICT (review_id) DO UPDATE SET message = excluded.message, updated_at = now()
RETURNING created_at, updated_at
`

type UpsertReplyParams struct {
	ReviewID string
	VendorID string
	Message  string
}

type UpsertReplyRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertReply(ctx context.Context, arg UpsertReplyParams) (UpsertReplyRow, error) {
	row := q.db.QueryRow(ctx, upsertReply, arg.ReviewID, arg.VendorID, arg.Message)
	var i UpsertReplyRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const vendorSummary = `-- name: VendorSummary :one
SELECT COALESCE(avg(rating), 0)::float8 AS rating_average, count(*) AS rating_count,
    count(*) FILTER (WHERE rating = 1) AS rated_1, count(*) FILTER (WHERE rating = 2) AS rated_2,
    count(*) FILTER (WHERE rating = 3) AS rated_3, count(*) FILTER (WHERE rating = 4) AS rated_4,
    count(*) FILTER (WHERE rating = 5) AS rated_5
FROM reviews WHERE vendor_id = $1 AND status = 'published' AND (verified_purchase OR $2::boolean)
`

type VendorSummaryParams struct {
	VendorID          string
	IncludeUnverified bool
}

type VendorSummaryRow struct {
	RatingAverage float64
	RatingCount   int64
	Rated1        int64
	Rated2        int64
	Rated3        int64
	Rated4        int64
	Rated5        int64
}

func (q *Queries) VendorSummary(ctx context.Context, arg VendorSummaryParams) (VendorSummaryRow, error) {
	row := q.db.QueryRow(ctx, vendorSummary, arg.VendorID, arg.IncludeUnverified)
	var i VendorSummaryRow
	err := row.Scan(
		&i.RatingAverage,
		&i.RatingCount,
		&i.Rated1,
		&i.Rated2,
		&i.Rated3,
		&i.Rated4,
		&i.Rated5,
	)
	return i, err
}
