// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package reviewdb

import (
	"context"
	"time"
)

const addUpload = `-- name: AddUpload :exec
INSERT INTO review_image_uploads (review_id, object_key) VALUES ($1, $2)
`

type AddUploadParams struct {
	ReviewID  string
	ObjectKey string
}

func (q *Queries) AddUpload(ctx context.Context, arg AddUploadParams) error {
	_, err := q.db.Exec(ctx, addUpload, arg.ReviewID, arg.ObjectKey)
	return err
}

const claimStaleUploads = `-- name: ClaimStaleUploads :many
UPDATE review_image_uploads u SET next_attempt_at = now() + interval '5 minutes'
WHERE u.object_key IN (SELECT object_key FROM review_image_uploads
    WHERE parked_at IS NULL AND next_attempt_at <= now() ORDER BY next_attempt_at LIMIT $1::int FOR UPDATE SKIP LOCKED)
RETURNING u.object_key, u.attempts, EXISTS (SELECT 1 FROM review_images i WHERE i.object_key = u.object_key) AS recorded
`

type ClaimStaleUploadsRow struct {
	ObjectKey string
	Attempts  int
	Recorded  bool
}

func (q *Queries) ClaimStaleUploads(ctx context.Context, batchSize int) ([]ClaimStaleUploadsRow, error) {
	rows, err := q.db.Query(ctx, claimStaleUploads, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimStaleUploadsRow
	for rows.Next() {
		var i ClaimStaleUploadsRow
		if err := rows.Scan(&i.ObjectKey, &i.Attempts, &i.Recorded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countImageSlots = `-- name: CountImageSlots :one
SELECT ((SELECT count(*) FROM review_images i WHERE i.review_id = $1::uuid)
    + (SELECT count(*) FROM review_image_uploads u WHERE u.review_id = $1::uuid AND u.parked_at IS NULL))::bigint AS slots
`

// Stored images plus uploads in progress (lock the review first so
// concurrent uploads queue up).
func (q *Queries) CountImageSlots(ctx context.Context, reviewID string) (int64, error) {
	row := q.db.QueryRow(ctx, countImageSlots, reviewID)
	var slots int64
	err := row.Scan(&slots)
	return slots, err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM review_image_uploads WHERE object_key = $1
`

func (q *Queries) DeleteUpload(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deleteUpload, objectKey)
	return err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO review_images (review_id, object_key, url, content_type, size_bytes, position)
SELECT $1::uuid, $2::text, $3::text, $4::text, $5::bigint, COALESCE(max(position) + 1, 0)
FROM review_images WHERE review_id = $1::uuid
RETURNING id, position, created_at
`

type InsertImageParams struct {
	ReviewID    string
	ObjectKey   string
	URL         string
	ContentType string
	SizeBytes   int64
}

type InsertImageRow struct {
	ID        string
	Position  int
	CreatedAt time.Time
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (InsertImageRow, error) {
	row := q.db.QueryRow(ctx, insertImage,
		arg.ReviewID,
		arg.ObjectKey,
		arg.URL,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i InsertImageRow
	err := row.Scan(&i.ID, &i.Position, &i.CreatedAt)
	return i, err
}

const uploadCleanupFailed = `-- name: UploadCleanupFailed :exec
UPDATE review_image_uploads SET attempts = attempts + 1, last_error = $1::text, next_attempt_at = $2,
    parked_at = CASE WHEN $3::boolean THEN now() END
WHERE object_key = $4
`

type UploadCleanupFailedParams struct {
	LastError     string
	NextAttemptAt time.Time
	Park          bool
	ObjectKey     string
}

func (q *Queries) UploadCleanupFailed(ctx context.Context, arg UploadCleanupFailedParams) error {
	_, err := q.db.Exec(ctx, uploadCleanupFailed,
		arg.LastError,
		arg.NextAttemptAt,
		arg.Park,
		arg.ObjectKey,
	)
	return err
}
